/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import Entity.IEntity;
import java.awt.Dimension;
import views.components.FormBuilder;
import views.components.FormTextField;
import views.components.IFormField;

/**
 *
 * @author rg
 */
public class EditView extends javax.swing.JFrame implements IEditView {

    private IEntity entity;
    private boolean isEditable;
    private boolean isModeNew;
    
    /**
     * Creates new form EditView
     */
    public EditView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panel_FormArea = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());
        add(filler1, java.awt.BorderLayout.LINE_START);
        add(filler2, java.awt.BorderLayout.LINE_END);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 50));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(600, 50));

        jButton1.setText("jButton1");
        jPanel2.add(jButton1);

        jButton2.setText("jButton2");
        jPanel2.add(jButton2);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        panel_FormArea.setLayout(new javax.swing.BoxLayout(panel_FormArea, javax.swing.BoxLayout.PAGE_AXIS));
        add(panel_FormArea, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_FormArea;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setEntity(IEntity entity) {
        this.entity = entity;
    }

    @Override
    public void setIsEditable(boolean editable) {
        this.isEditable = editable;
    }

    @Override
    public void setIsModeNew(boolean isNew) {
        this.isModeNew = isNew;
    }

    @Override
    public void build() {
        IFormField[] fields = new FormBuilder(this.entity, this.isModeNew).Build();
        
        for(IFormField field : fields) {
            FormTextField txt_field = (FormTextField) field;
            panel_FormArea.add(txt_field);
        }
        
        this.setSize(new Dimension(600, 200));
        this.setVisible(true);
    }
}
