package views;

import Entity.Cidade;
import Entity.IEntity;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import orm.IORM;

/**
 *
 * @author rg
 */
public class ListView extends javax.swing.JFrame {

    IORM orm;
    IEditView editView;
    DefaultTableModel tableModel;
    
    /**
     * Creates new form ListView
     */
    public ListView(IORM orm, IEditView editView, String title) {
        this.setTitle(title);
        this.orm = orm;
        this.editView = editView;
        
        this.tableModel = this.setTableModel("");
        
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        title_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_busca = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_excluir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_adicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));
        jPanel1.setLayout(new java.awt.BorderLayout(10, 10));

        jTable1.setModel(this.tableModel);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setRowHeight(25);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(601, 50));
        jPanel2.setLayout(new java.awt.GridLayout(1, 7, 5, 0));

        title_label.setText(this.getTitle());
        title_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(title_label);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Busca:");
        jPanel2.add(jLabel1);
        jPanel2.add(txt_busca);

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_buscar);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        jPanel3.add(btn_excluir);

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_editar);

        btn_adicionar.setText("Novo");
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_adicionar);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Métodos Customizados
     */
    private DefaultTableModel setTableModel(String searchTerm) {
        String whereClause = "WHERE descricao LIKE %'"
                + searchTerm 
                + "'%;";
        
        return new DefaultTableModel(
                this.orm.toJTable(whereClause),
                this.orm.getJTableColumns()
        );
    }
    
    
    /*
     * OnAction
     */
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed
        IEditView form = new EditView();
        form.setEntity(new Cidade());
        form.setIsEditable(true);
        form.setIsModeNew(true);
        form.build();
    }//GEN-LAST:event_btn_adicionarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        IEditView form = new EditView();
        form.setEntity(this.getItemFromTable());
        form.setIsEditable(true);
        form.setIsModeNew(true);
        form.build();
    }//GEN-LAST:event_btn_editarActionPerformed

    private IEntity getItemFromTable() {
        //Buscar o cliente de acordo com a linha selecionada na tabela de visualização
        int rowIndex = jTable1.getSelectedRow();
        int ormItemId = Integer.parseInt(((Vector) this.tableModel.getDataVector().elementAt(rowIndex)).elementAt(0).toString());
        return (IEntity) orm.getById(ormItemId);
    }
    
    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_excluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel title_label;
    private javax.swing.JTextField txt_busca;
    // End of variables declaration//GEN-END:variables
}
