package views.components;

import views.*;
import entity.IEntity;
import entity.forms.FormBase;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import orm.IORM;

/**
 *
 * @author rg
 */
public class SearchableTable extends javax.swing.JPanel implements ISearchableTable {

    IORM orm;
    DefaultTableModel tableModel;
    FormBase form;
    String searchColumn;

    
    /**
     * Creates new form ListView
     * @param orm the orm used to access the data
     * @param editView the edit view class
     * @param title title of the window
     * @param searchColumn the column used for searching
     */
    public SearchableTable(IORM orm, String title) {
        this.setTitle(title);
        this.orm = orm;
        
        this.tableModel = this.setTableModel("");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        title_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_busca = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));
        jPanel1.setLayout(new java.awt.BorderLayout(10, 10));

        jTable1.setModel(this.tableModel);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setRowHeight(25);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(601, 50));
        jPanel2.setLayout(new java.awt.GridLayout(1, 7, 5, 0));

        title_label.setText(this.getTitle());
        title_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(title_label);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Busca:");
        jPanel2.add(jLabel1);
        jPanel2.add(txt_busca);

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_buscar);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Métodos Customizados
     */
    private DefaultTableModel setTableModel(String searchTerm) {
        /**
         * Set the table model based on the search term in the search field
         */
        
        String whereClause = "WHERE " + this.searchColumn + " ILIKE %'"
                + searchTerm 
                + "'%;";
        
        return new DefaultTableModel(
                this.orm.toJTable(whereClause),
                this.orm.getJTableColumns()
        );
    }
    
    @Override
    public void updateTable() {
        /**
         * Updates the table and table model in the view
         */
        this.tableModel = this.setTableModel(txt_busca.getText());
        jTable1.setModel(tableModel);
        this.tableModel.fireTableDataChanged();
    }
    
    /*
     * OnAction
     */
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        this.updateTable();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void openForm(IEntity entity) {
        this.form.setup(entity, orm);
        this.form.populateForm();

        this.editView = new EditView(this);
        editView.setForm(form);
        editView.setWindowTitle(form.getFormName());
        editView.build();
    }
    
    private IEntity getItemFromTable() throws IndexOutOfBoundsException {
        /**
         * Gets the selected table item
         * @Returns the selected Item from the table
         * @Throws IndexOutOfBoundsException if no item is selected
         */
        int rowIndex = jTable1.getSelectedRow();
        int ormItemId = Integer.parseInt(((Vector) this.tableModel.getDataVector().elementAt(rowIndex)).elementAt(0).toString());
        return (IEntity) orm.getById(ormItemId);
    }
    
    private void openInformationPane(String msg) {
        JOptionPane.showMessageDialog(
                this, 
                msg);
    }
    
    private int openConfirmationPane(String msg) {
        return JOptionPane.showConfirmDialog(
            this, 
            msg);
    }

    public void setForm(FormBase form) {
        this.form = form;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel title_label;
    private javax.swing.JTextField txt_busca;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setORM(IORM orm) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public Object getSelectedItem() {
    }
}
